#!/bin/bash
#
# Set up a macOS-hosted cross toolchain for building aarch64 Sailfish OS
# packages directly on an arm64 Mac, without a build engine VM.
#
# Creates ~/invariant/tooling-mac/bin/aarch64-meego-linux-gnu-{gcc,cc,clang}
# wrapper scripts around Homebrew clang + lld, using a Sailfish OS aarch64
# target rootstrap (the same file the SDK installs as a build target) as the
# sysroot. Packages can then be built with rpmbuild (Homebrew rpm).
#
# Usage:
#    setup-cross-tooling-mac.sh [OPTION]
#
# Options:
#    -s  | --sysroot <DIR>      aarch64 target rootstrap directory
#                               [$DEF_QT... see SYSROOT below]
#    -h  | --help               this help
#
# Example - build a package:
#    export PATH=~/invariant/tooling-mac/bin:$PATH
#    rpmbuild -ba --target aarch64 --define '_prefix /usr' my.spec
#
# Copyright (C) 2026 Nicolaj Hartmann
# License: BSD (same as the other scripts in this repository)
#

. $(dirname $0)/defaults.sh

SYSROOT=$DEF_PREFIX/invariant/targets-test
TOOLING_DIR=$DEF_PREFIX/invariant/tooling-mac

usage() {
    cat <<EOF
Set up a macOS-hosted cross toolchain for aarch64 Sailfish OS packages

Prerequisites:
 - Homebrew packages: llvm lld rpm coreutils gnu-sed
 - aarch64 target rootstrap (Sailfish_OS-*-Sailfish_SDK_Target-aarch64)
   unpacked at [$SYSROOT]

Creates wrappers in [$TOOLING_DIR/bin]

EOF
    [[ -n "$1" ]] && exit 1
}

# handle commandline options
while [[ ${1:-} ]]; do
    case "$1" in
    -s | --sysroot ) shift
        SYSROOT=$1; shift
        ;;
    -h | --help ) shift
        usage quit
        ;;
    * )
        usage quit
        ;;
    esac
done

if [[ $(uname -s) != "Darwin" ]] || [[ $UNAME_ARCH != "arm64" ]]; then
    fail "this script is for arm64 macOS hosts"
fi

for tool in /opt/homebrew/opt/llvm/bin/clang /opt/homebrew/opt/lld/bin/ld.lld rpmbuild; do
    [[ -x $(command -v ${tool##*/}) ]] || [[ -x $tool ]] || fail "missing: $tool (brew install llvm lld rpm)"
done

[[ -d $SYSROOT/usr/include ]] || fail "no usr/include in sysroot [$SYSROOT]"
[[ -f $SYSROOT/usr/lib64/crt1.o ]] || fail "no usr/lib64/crt1.o in sysroot [$SYSROOT]"

mkdir -p $TOOLING_DIR/bin

cat > $TOOLING_DIR/bin/aarch64-meego-linux-gnu-gcc <<EOF
#!/bin/bash
# Cross-compiler wrapper: macOS-hosted clang -> aarch64 Sailfish target
# Generated by $(basename $0); sysroot: $SYSROOT
SYSROOT="\${SAILFISH_SYSROOT:-$SYSROOT}"
CLANG=/opt/homebrew/opt/llvm/bin/clang
LLD=/opt/homebrew/opt/lld/bin/ld.lld
mode=link
for a in "\$@"; do
    case "\$a" in
        -c|-S|-E|-M|-MM|-fsyntax-only) mode=nolink ;;
    esac
done
if [ "\$mode" = link ]; then
    exec "\$CLANG" --target=aarch64-meego-linux-gnu --sysroot="\$SYSROOT" \\
        -fuse-ld="\$LLD" -Qunused-arguments -nostdlib \\
        "\$@" \\
        "\$SYSROOT"/usr/lib64/crt1.o "\$SYSROOT"/usr/lib64/crti.o \\
        -lc -l:libgcc_s.so.1 "\$SYSROOT"/usr/lib64/crtn.o
else
    exec "\$CLANG" --target=aarch64-meego-linux-gnu --sysroot="\$SYSROOT" \\
        -Qunused-arguments "\$@"
fi
EOF
chmod +x $TOOLING_DIR/bin/aarch64-meego-linux-gnu-gcc
ln -sf aarch64-meego-linux-gnu-gcc $TOOLING_DIR/bin/aarch64-meego-linux-gnu-cc
ln -sf aarch64-meego-linux-gnu-gcc $TOOLING_DIR/bin/aarch64-meego-linux-gnu-clang

echo "Cross toolchain ready: $TOOLING_DIR/bin"
echo "Add it to PATH and build aarch64 RPMs with rpmbuild --target aarch64"
echo "(note: use --define '_prefix /usr' so paths match Sailfish OS)"
